# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(db_index=True, max_length=200, null=True, verbose_name='任务名称')),
                ('partment', models.CharField(db_index=True, max_length=200, null=True, verbose_name='部门')),
                ('types', models.CharField(choices=[('定时任务', '定时任务'), ('循环任务', '循环任务')], max_length=64, verbose_name='任务类型')),
                ('taskfunc', models.CharField(max_length=100, verbose_name='任务函数')),
                ('para', models.CharField(help_text='字典', max_length=100, verbose_name='时间参数')),
                ('memo', models.CharField(max_length=400, verbose_name='说明')),
                ('is_active', models.IntegerField(verbose_name='是否停止')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('task_id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, verbose_name='UUID')),
                ('state', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, max_length=64, verbose_name='状态')),
                ('memo', models.CharField(max_length=400, verbose_name='备注')),
                ('runtime', models.FloatField(help_text='时间秒', null=True, verbose_name='执行时间')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('taskname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.TaskItem')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
    ]
