# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRepayMoney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allRepayMoney', models.IntegerField(default=0)),
                ('acRepayMoney', models.IntegerField(default=0)),
                ('repayRate', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.DeleteModel(
            name='FlowPaidMoney',
        ),
    ]
