# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180413_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdelayrate',
            name='termDate',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
