# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_flowdelayrate_termdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdelayrate',
            name='firmId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowloanmoneyno',
            name='firmId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowrepaymoney',
            name='firmId',
            field=models.IntegerField(default=0),
        ),
    ]
