# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIncrease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register', models.IntegerField(default=0)),
                ('allow', models.IntegerField(default=0)),
                ('newApply', models.IntegerField(default=0)),
                ('oldApply', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
