# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age1', models.IntegerField(default=0, verbose_name='18岁及以下')),
                ('age2', models.IntegerField(default=0, verbose_name='19-25岁')),
                ('age3', models.IntegerField(default=0, verbose_name='26-33岁')),
                ('age4', models.IntegerField(default=0, verbose_name='34-41岁')),
                ('age5', models.IntegerField(default=0, verbose_name='42岁及以上')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
