# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(default='china', max_length=32)),
                ('numInCity', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tradeMoney', models.IntegerField(default=0)),
                ('tradeNum', models.IntegerField(default=0)),
                ('activeUser', models.IntegerField(default=0)),
                ('sumUser', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexHopper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register', models.IntegerField(default=0)),
                ('applys', models.IntegerField(default=0)),
                ('passs', models.IntegerField(default=0)),
                ('loan', models.IntegerField(default=0)),
                ('reloan', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
