# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmId', models.IntegerField(default=0)),
                ('productId', models.IntegerField(default=0)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
